version: 2
jobs:
  rubocop:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: rm docker-compose.override.yml
          command: rm docker-compose.override.yml
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: run rubocop
          command: docker-compose run web bundle exec rubocop
workflows:
  version: 2
  test-pullrequest:
    jobs:
      - rubocop
